### ISSUE TITLE
0.9.1 depends on an unreleased version of ssh-forever

### ISSUE THREAD

**Issue by technicalpickles** [auxesis/cucumber-nagios#72]
Ran into this while trying to install 0.9.1:

```
ERROR:  Error installing cucumber-nagios:
        cucumber-nagios requires ssh-forever (>= 0.4.0, runtime)
```

I checked over on [rubygems.org](http://rubygems.org/gems/ssh-forever) and it's showing 0.2.3 is the latest ssh-forever. Looks like this was introduced with the recent release 0.9.1, as 0.9.0 worked like a charm.

**Comment by hedgehog** [comment]
Hmm, I just joined Lindasy's repo and rubygems, so apologies if this is a bit unhelpful.  The ssh-forever dependency was in a pull request I made but as far as I can tell it was - correctly - not pulled into master.

ssh-forever is not in the gemspec nor the Gemfile.lock, so it seems this might be in the source that Lindasy released to rubygems?

So it seems this is a bug that is best fixed by pulling the 0.9.1 release.  Lindsay, you agree?  I'll leave a release up to you - I'm busy trying to get Cuken working with Chef 0.10.0, then get it out the door.

**Comment by technicalpickles** [comment]
I didn't dig into it deeply, but yeah it's looking like ssh-forever isn't a dependency according to current master. Is there a chance a release was done on a branch or something weird?

**Comment by hedgehog** [comment]
Looks that way.  I'll have to let Lindsay sort this out, since I'm not sure what fix/patch he was trying to get out there.

**Comment by auxesis** [comment]
Hmm, I mucked that merge up. Yanked the gem, and I'll try the merge again.

**Comment by josephholsten** [comment]
https://github.com/auxesis/cucumber-nagios/pull/83 removes ssh-forever, which is no longer used by cuken.
