### ISSUE TITLE
Create a permanant fork of ssh-forever

### ISSUE THREAD

**Issue by josephholsten** [auxesis/cucumber-nagios#75]
Since mattwaynne isn't going to merge in the changes for ssh-forever, we need to release those changes in an actual gem or merge them into cuken or cucumber-nagios.

**Comment by hedgehog** [comment]
Done, currently my ssh-forever changes do sit in cuken, they just need to be integrated into some steps.
After some experience I think passwordless ssh access can be simplified beyond what was in ssh-forever.

Comments on:

```
Scenario: Initialize interactive password-less SSH access:
When I interactively run SSH sessions:
  | user      | hostname   | name         | port        |
  | :default  | :default   | :default     | :default    |
And I type "echo $SSH_CLIENT"
And I type "echo $SSH_CONNECTION"
Then I type "exit"
And the output contains "..."

Scenario: Initialize batch password-less SSH access:
When I run SSH sessions:
  | user      | hostname   | name         | port        | command |
  | :default  | :default   | :default     | :default    | "echo $SSH_CLIENT\necho $SSH_CONNECTION"
Then the output contains "..."
```

I have some changes to do this sitting in my local repo, I'd like to clean up before pusshing to github because the sate of cucken is getting a little messy - unavoidable because I needed something that worked yesterday - but I think that will hinder adoption.
Issue is how to allow other ssh options.

If you want to, please open an issue on cuken with this detail I'll tag it 0.2

**Comment by josephholsten** [comment]
Does this mean both can remove their dependency on ssh-forever?

**Comment by hedgehog** [comment]
On Tue, Jun 28, 2011 at 9:52 AM, josephholsten
reply@reply.github.com
wrote:

> Does this mean both can remove their dependency on ssh-forever?

Eventually yes.
For cucken hopefully at 0.2

> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/auxesis/cucumber-nagios/issues/75#issuecomment-1451335

## 

πόλλ' οἶδ ἀλώπηξ, ἀλλ' ἐχῖνος ἓν μέγα
[The fox knows many things, but the hedgehog knows one big thing.]
  Archilochus, Greek poet (c. 680 BC – c. 645 BC)
http://hedgehogshiatus.com
